#logging:
#  level:
#    root: ERROR
##  charset:
##      console: "UTF-8"

#logging:
#  config: logback.xml

spring:
#  main:
#    banner-mode: "off"
  output:
    ansi:
      enabled: always
#  output:
#    ansi:
#      enabled: detect

#picocli:
#  usage:
#    width: 120

  application:
    name: ParaCoder

    admin:
      enabled: false

  jmx:
    enabled: false

  sql:
    init:
      enabled: false

  config:
    # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.files.importing
    import: "file:paracoder_commands.yml"
